# Generated by Django 4.2.7 on 2026-04-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("telefone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "rede_social",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cep", models.CharField(blank=True, max_length=20, null=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=255, null=True)),
                ("cidade", models.CharField(blank=True, max_length=255, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("unidade", "unidade"),
                            ("cone", "cone"),
                            ("metro", "metro"),
                            ("kg", "kg"),
                            ("rolo", "rolo"),
                            ("pecas", "peças"),
                        ],
                        default="unidade",
                        max_length=20,
                    ),
                ),
                (
                    "quantidade_atual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estoque_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("imagem_url", models.TextField(blank=True, null=True)),
                (
                    "preco_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tempo_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subcategoria",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("peca", "Peça"), ("bordado", "Bordado")],
                        default="peca",
                        max_length=16,
                    ),
                ),
                ("quantidade_pontos", models.IntegerField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha_hash", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pedido", models.DateField(blank=True, null=True)),
                ("prazo", models.DateField(blank=True, null=True)),
                ("data_entrega", models.DateField(blank=True, null=True)),
                (
                    "canal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Instagram", "Instagram"),
                            ("WhatsApp", "WhatsApp"),
                            ("Facebook", "Facebook"),
                            ("Marketplace", "Marketplace"),
                            ("Outro", "Outro"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pix", "Pix"),
                            ("Dinheiro", "Dinheiro"),
                            ("Cartao", "Cartão"),
                            ("Transferencia", "Transferência"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Parcial", "Parcial"),
                            ("Pago", "Pago"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("urgente", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("motivo_cancelamento", models.TextField(blank=True, null=True)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Recebido", "Recebido"),
                            ("Aguardando Matriz", "Aguardando Matriz"),
                            ("Em Producao", "Em Produção"),
                            ("Pronto para Entrega", "Pronto para Entrega"),
                            ("Entregue", "Entregue"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Recebido",
                        max_length=32,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="commerce.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "entrada"), ("saida", "saída")],
                        max_length=16,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=12)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="commerce.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peca", models.CharField(blank=True, max_length=255, null=True)),
                ("descricao_bordado", models.TextField(blank=True, null=True)),
                ("quantidade", models.IntegerField(default=1)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="commerce.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="commerce.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="commerce.pedido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historico",
                        to="commerce.usuario",
                    ),
                ),
            ],
        ),
    ]
