# Generated by Django 4.2.7 on 2026-09-15 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_rules_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_size', models.CharField(choices=[('standard', 'Padrão'), ('large', 'Grande'), ('extra_large', 'Extra grande')], default='standard', max_length=16)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('highlight_links', models.BooleanField(default=False)),
                ('readable_font', models.BooleanField(default=False)),
                ('increased_spacing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_profile', to='commerce.usuario')),
            ],
        ),
    ]
